# Generated by Django 5.2.1 on 2025-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_opportunite', models.CharField(max_length=100)),
                ('nom_client', models.CharField(max_length=255)),
                ('type_garantie', models.CharField(max_length=100)),
                ('type_bien', models.CharField(max_length=100)),
                ('destination_ouvrage', models.CharField(max_length=100)),
                ('types_travaux', models.CharField(max_length=100)),
                ('cout_ouvrage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presence_existant', models.BooleanField()),
                ('client_vip', models.BooleanField()),
                ('souhaite_rcmo', models.BooleanField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
