# Generated by Django 5.2.1 on 2025-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_franchise_batiment_devis_franchise_cat_nat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='prime_seule_do',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='prime_seule_trc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_seul_do',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_seul_trc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='vendeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
